'use client'
import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'

type AdminData={users:{id:string;name:string;email:string;role:string;city:string;blocked:number}[];orders:{id:string;title:string;client_name:string;pro_name:string|null;status:string;city:string;budget:number;agreed_price:number|null;address:string}[];reviews:{order_id:string;client_name:string;pro_name:string;rating:number;body:string}[];audit:{id:string;target_id:string;action:string;reason:string;created_at:string}[]}
const names:Record<string,string>={open:'Открыт',assigned:'Мастер выбран',in_progress:'В работе',awaiting_confirmation:'На подтверждении',completed:'Выполнен',cancelled:'Отменён',cancelOrder:'Заказ отменён',blockUser:'Аккаунт заблокирован',unblockUser:'Аккаунт разблокирован'}
export default function AdminConsole(){
 const [data,setData]=useState<AdminData|null>(null)
 const [error,setError]=useState('')
 const [tab,setTab]=useState('orders')
 const [busy,setBusy]=useState(false)
 const [query,setQuery]=useState('')
 const [action,setAction]=useState<{id:string;action:string;title:string}|null>(null)
 const refresh=useCallback(async()=>{const r=await fetch('/api/admin',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)},[])
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[refresh])
 const matches=(value:string)=>value.toLowerCase().includes(query.toLowerCase())
 return <div className="usta-app"><header className="usta-header"><Link className="usta-logo" href="/">usta<span>●</span></Link><span className="usta-tagline">Управление платформой</span><div className="usta-header-right"><Link href="/">На сайт</Link><Link href="/logout">Выйти</Link></div></header><main className="usta-main"><div className="usta-dashboard-title"><div className="usta-eyebrow">АДМИНИСТРАТОР</div><h1>Обзор платформы</h1><p>Заказы, пользователи и действия модерации из постоянной базы.</p></div>{error&&<div className="usta-error" role="alert">{error}</div>}{!data?<p>Загрузка…</p>:<><div className="usta-stats"><div><span>Пользователей</span><strong>{data.users.length}</strong></div><div><span>Заказов</span><strong>{data.orders.length}</strong></div><div><span>Завершено</span><strong>{data.orders.filter(o=>o.status==='completed').length}</strong></div></div><nav className="usta-tabs" aria-label="Разделы администратора">{[['orders','Заказы'],['users','Пользователи'],['reviews','Отзывы'],['audit','Журнал']].map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>{setTab(id);setQuery('')}}>{label}</button>)}<button className="usta-refresh" onClick={()=>refresh().catch(e=>setError(e.message))}>Обновить</button></nav><div className="usta-filters"><label className="usta-search"><input aria-label="Поиск в админке" placeholder="Поиск по имени, заказу или email" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="usta-order-grid">
 {tab==='orders'&&data.orders.filter(o=>matches(`${o.title} ${o.client_name} ${o.pro_name}`)).map(o=><article key={o.id} className="usta-pro-card"><span className={`usta-status ${o.status}`}>{names[o.status]}</span><h3 style={{marginTop:14}}>{o.title}</h3><p>Клиент: {o.client_name}<br/>Мастер: {o.pro_name||'Не выбран'}<br/>{o.city}, {o.address}</p><p>{new Intl.NumberFormat('ru-RU').format(o.agreed_price||o.budget)} сум</p>{!['completed','cancelled'].includes(o.status)&&<button className="usta-text-button" onClick={()=>setAction({id:o.id,action:'cancelOrder',title:`Отменить: ${o.title}`})}>Отменить с указанием причины</button>}</article>)}
 {tab==='users'&&data.users.filter(u=>matches(`${u.name} ${u.email}`)).map(u=><article key={u.id} className="usta-pro-card"><h3>{u.name}</h3><p>{u.email}<br/>{u.role==='pro'?'Мастер':'Клиент'} · {u.city}<br/>{u.blocked?'Заблокирован':'Активен'}</p><button className="usta-text-button" onClick={()=>setAction({id:u.id,action:u.blocked?'unblockUser':'blockUser',title:`${u.blocked?'Разблокировать':'Заблокировать'}: ${u.name}`})}>{u.blocked?'Разблокировать':'Заблокировать'}</button></article>)}
 {tab==='reviews'&&data.reviews.filter(r=>matches(`${r.client_name} ${r.pro_name} ${r.body}`)).map(r=><article key={r.order_id} className="usta-pro-card"><h3>{r.rating}/5 ★ · {r.pro_name}</h3><p>От клиента: {r.client_name}</p><p>{r.body}</p></article>)}
 {tab==='audit'&&data.audit.filter(a=>matches(`${a.action} ${a.reason}`)).map(a=><article key={a.id} className="usta-pro-card"><h3>{names[a.action]}</h3><p>{a.reason}</p><p>{new Date(a.created_at).toLocaleString('ru-RU')}<br/>ID: {a.target_id}</p></article>)}
 </div>{((tab==='orders'&&!data.orders.length)||(tab==='users'&&!data.users.length)||(tab==='reviews'&&!data.reviews.length)||(tab==='audit'&&!data.audit.length))&&<div className="usta-empty"><h3>Записей пока нет</h3><p>Здесь появятся данные реальных действий в приложении.</p></div>}</>}</main>{action&&<div className="usta-backdrop"><section className="usta-modal" role="dialog" aria-modal="true" aria-labelledby="moderation-title"><button className="usta-close" onClick={()=>setAction(null)} aria-label="Закрыть">×</button><h2 id="moderation-title">{action.title}</h2><form className="usta-form" onSubmit={async e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');setBusy(true);setError('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...action,reason})});const result=await r.json();if(!r.ok)throw new Error(result.error);await refresh();setAction(null)}catch(e){setError(e instanceof Error?e.message:'Ошибка запроса');setAction(null)}finally{setBusy(false)}}}><label>Причина действия<textarea name="reason" minLength={5} maxLength={1000} required/></label><p>Действие и причина сохранятся в журнале. Блокировка завершит все сессии пользователя.</p><button disabled={busy} className="usta-button">Подтвердить действие</button></form></section></div>}</div>
}
