'use client'
import {useState} from 'react'
import {services} from '@/lib/services.mjs'
const money=(n:number)=>new Intl.NumberFormat('ru-RU').format(n)+' сум'
export function ServiceFields({initial='other'}:{initial?:string}){
 return <><label>Вид работы для сравнения цены<select name="serviceCode" defaultValue={initial}>{services.map(s=><option key={s.code} value={s.code}>{s.label} · {s.unit}</option>)}</select></label><div className="usta-two-fields"><label>Количество единиц<input name="quantity" type="number" min={1} max={1000} defaultValue={1} required/></label><label>Что входит в бюджет<select name="priceBasis" defaultValue="unknown"><option value="unknown">Ещё не согласовано</option><option value="labor">Работа без материалов</option><option value="total">Работа и материалы</option></select></label></div><label className="usta-ai-consent"><input name="priceOptIn" type="checkbox"/> Включить сумму завершённого заказа в обезличенную статистику цен</label></>
}
export default function PriceInsight({city,initialService='tap_replace',initialBasis='labor',initialQuantity=1,initialQuote=''}:{city:string;initialService?:string;initialBasis?:string;initialQuantity?:number;initialQuote?:string}){
 const [result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 return <section className="usta-panel usta-price"><div className="usta-eyebrow">ЦЕНЫ БЕЗ ДОГАДОК</div><h3>Сравнить предложение</h3><p>Согласованные цены завершённых заказов USTA за 180 дней. Это ориентир по выборке, а не рыночный тариф.</p><form className="usta-form" onChange={()=>setResult(null)} onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{const res=await fetch('/api/platform',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'priceStats',...data})});const value=await res.json();if(!res.ok)throw Error(value.error);setResult(value)}catch(e){setError(e instanceof Error?e.message:'Нет соединения')}finally{setBusy(false)}}}>
 <div className="usta-two-fields"><label>Вид работы<select name="serviceCode" defaultValue={initialService}>{services.map(s=><option key={s.code} value={s.code}>{s.label} · {s.unit}</option>)}</select></label><label>Город<input name="city" defaultValue={city} minLength={2} maxLength={80} required/></label></div>
 <div className="usta-two-fields"><label>Состав цены<select name="priceBasis" defaultValue={initialBasis==='unknown'?'labor':initialBasis}><option value="labor">Работа без материалов</option><option value="total">Работа и материалы</option></select></label><label>Количество единиц<input name="quantity" type="number" min={1} max={1000} defaultValue={initialQuantity} required/></label></div>
 <label>Предложенная сумма целиком, сум<input name="quote" type="number" min={1000} max={100000000} defaultValue={initialQuote} placeholder="Можно оставить пустым"/></label><button className="usta-button secondary" disabled={busy}>{busy?'Сравниваем…':'Показать статистику'}</button></form>
 {error&&<p role="alert">{error}</p>}{result&&<div aria-live="polite" className="usta-ai-result">{result.status==='insufficient'?<><strong>Пока недостаточно данных</strong><p>Найдено {result.count} независимых пар клиент–мастер. Нужно минимум 5 заказов от 3 клиентов и 3 мастеров. Для комплексных работ сравнение не рассчитывается.</p></>:<><strong>Средняя цена: {money(result.mean)} / {result.service.unit}</strong><p>Медиана: {money(result.median)}. Средние 50% наблюдений: {money(result.low)}–{money(result.high)}.</p><p>Выборка: {result.count} заказов.</p>{result.comparison&&<p>{result.comparison==='above'?'Цена выше центрального диапазона выборки. Попросите уточнить объём, сложность, срочность и материалы.':result.comparison==='below'?'Цена ниже центрального диапазона. Уточните, включены ли выезд и все работы.':'Цена внутри центрального диапазона выборки.'}</p>}</>}<small>Сложность и качество могут отличаться. По одной цене нельзя определить обман. {result.source}</small></div>}
 </section>
}
