import assert from 'node:assert/strict';
const base=process.env.USTA_TEST_URL || 'http://127.0.0.1:3000';
const post=(path,body,cookie='',origin=base)=>fetch(base+path,{method:'POST',headers:{origin,'Content-Type':'application/json',cookie},body:JSON.stringify(body)});
assert.equal((await fetch(base+'/')).status,200);
assert.equal((await fetch(base+'/api/admin')).status,401);
assert.equal((await post('/api/platform',{action:'createOrder'})).status,401);
assert.equal((await post('/api/platform',{action:'logout'},'','https://invalid.example')).status,403);
assert.equal((await fetch(base+'/api/platform',{method:'POST',headers:{origin:base,'Content-Type':'application/json'},body:'{'})).status,400);
assert.equal((await post('/api/platform',{action:'logout'})).status,200);
const login=await post('/api/login',{password:process.env.ADMIN_PASSWORD});
assert.equal(login.status,200);
const adminCookie=login.headers.getSetCookie()[0].split(';')[0];
const admin=await fetch(base+'/api/admin',{headers:{cookie:adminCookie}});
assert.equal(admin.status,200);
const data=await admin.json();
assert.ok(Array.isArray(data.users)&&Array.isArray(data.orders)&&Array.isArray(data.audit));
assert.ok(data.users.every(u=>!('password' in u)&&!('salt' in u)));
assert.equal((await post('/api/admin',{action:'invalid'},adminCookie,'https://invalid.example')).status,403);
assert.equal((await post('/api/admin',{action:'invalid',id:'x',reason:'verification'},adminCookie)).status,400);
assert.equal((await post('/api/logout',{},adminCookie)).status,200);
console.log(`HTTP checks passed. Admin sees ${data.users.length} users and ${data.orders.length} orders. No data changed apart from login cookies.`);
